name: Build Installers

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: 'preview'

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      # Checkout do repositório
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      
      # Checkout do branch ou tag específico
      - run: git checkout ${{ github.ref_name }}
        working-directory: ./traccar-web

      # Setup do Java
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle
      
      # Construção do projeto Java
      - run: ./gradlew build

      # Setup do Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: npm
          cache-dependency-path: traccar-web/package-lock.json
      
      # Instalar dependências e construir o frontend
      - run: npm ci && npm run build
        working-directory: ./traccar-web

      # Instalar dependências do sistema
      - run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y libgcc-s1:i386 libstdc++6:i386
          sudo apt-get install -y innoextract makeself wine32 s3cmd

      # Baixar dependências e construir instaladores
      - name: Build installers
        working-directory: ./setup
        run: |
          wget -q http://files.jrsoftware.org/is/5/isetup-5.5.6.exe
          wget -q https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.4+7/OpenJDK21U-jdk_x64_windows_hotspot_21.0.4_7.zip
          wget -q https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.4+7/OpenJDK21U-jdk_x64_linux_hotspot_21.0.4_7.tar.gz
          wget -q https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.4+7/OpenJDK21U-jdk_aarch64_linux_hotspot_21.0.4_7.tar.gz
          ./package.sh ${{ github.event.inputs.version }}

      # Criação de uma release no GitHub
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: ./setup/traccar-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
