name: Build and Release Installers

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: 'preview'

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      # Checkout do código-fonte
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      # Checkout na branch especificada
      - name: Checkout specified branch
        run: git checkout ${{ github.ref_name }}
        working-directory: ./traccar-web

      # Configuração do ambiente Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      # Build do projeto com Gradle
      - name: Build with Gradle
        run: ./gradlew build

      # Configuração do ambiente Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: npm
          cache-dependency-path: traccar-web/package-lock.json

      # Instalação das dependências Node.js e build
      - name: Build frontend
        run: npm ci && npm run build
        working-directory: ./traccar-web

      # Instalação das dependências de sistema para os instaladores
      - name: Install dependencies for installers
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install libgcc-s1:i386 libstdc++6:i386
          sudo apt-get install innoextract makeself wine32 s3cmd

      # Download e execução do script de build dos instaladores
      - name: Build installers
        working-directory: ./setup
        run: |
          wget -q http://files.jrsoftware.org/is/5/isetup-5.5.6.exe
          wget -q https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.4+7/OpenJDK21U-jdk_x64_windows_hotspot_21.0.4_7.zip
          wget -q https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.4+7/OpenJDK21U-jdk_x64_linux_hotspot_21.0.4_7.tar.gz
          wget -q https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.4+7/OpenJDK21U-jdk_aarch64_linux_hotspot_21.0.4_7.tar.gz
          ./package.sh ${{ github.event.inputs.version }}

      # Upload dos instaladores para o espaço no S3
      - name: Upload installers to S3
        working-directory: ./setup
        env:
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
        run: |
          s3cmd --acl-public put traccar-*.zip s3://traccar/builds/ --host=nyc3.digitaloceanspaces.com --host-bucket=traccar --access_key="$S3_ACCESS_KEY" --secret_key="$S3_SECRET_KEY"

      # Criação de release no GitHub e upload dos instaladores
      - name: Create GitHub release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: ./setup/traccar-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Adicionar tag à release
      - name: Tag release
        run: |
          git tag -a "v${{ github.event.inputs.version }}" -m "Release version ${{ github.event.inputs.version }}"
          git push origin "v${{ github.event.inputs.version }}"
